[programs.devnet]
mysolanaapp = "9WSTCnLnpovgyoyCEbhpzAfSLezPXmkS3F67rSUWAeam"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jaylee/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
